project/main/routes.py
from flask import Blueprint,render_template, redirect, url_for, request, flash, jsonify
from flask_login import login_required, current_user
from project.models import Item, Cart, Item_Type,Defined_Items, Cart_Items, Orders, Order_Items, Reviews
from project.main.forms import AddToCart, WriteReview
from project import db, whooshee
import paypalrestsdk
import stripe

main = Blueprint('main',__name__, template_folder='templates',static_folder='static',static_url_path='/main/static')

pub_key = 'pk_test_y0kbNWMwHrkmLDHTTGPVSbGi00JHpiOo4u'
secret_key = 'sk_test_QrZUDZ7oiRfB7ar1c9GMewMp00wTwWj2uD'

stripe.api_key = secret_key

@main.context_processor
def inject_types():
	types = Item_Type.query.all()
	return dict(types=types)

paypalrestsdk.configure({
  "mode": "sandbox", # sandbox or live
  "client_id": "Ad1nZ9jJPoj3Gvp_7h_bnGKEGFtiuHwYlYnbftyxbii0JkIfbML46o2KtvzDfAyEVo8L-cjpJhKry9dT",
  "client_secret": "EHxDcsiAx7NrFBjwufUKKw7hU29Ovba0ZOM6Fe6F86SU3TpVfmvSrl_9YYACK0M9dXKxeLw6MB7WoF1wEHxDcsiAx7NrFBjwufUKKw7hU29Ovba0ZOM6Fe6F86SU3TpVfmvSrl_9YYACK0M9dXKxeLw6MB7WoF1w" })

@main.route('/')
def index():
	items = Item.query.all()
	return render_template('main.html',title='Home',items=items)


@main.route('/price_up/<name>')
@login_required
def price_up(name):
	Item.query.order_by(Item.price.asc()).all()
	db.session.commit() 

	return redirect(url_for(name))

@main.route('/price_down/<name>')
@login_required
def price_down(name):
	Item.query.order_by(Item.price.desc()).all()
	db.session.commit() 

	return redirect(url_for(name))

@main.route('/search',methods=['GET','POST'])
def search():
	search = request.args.get('search')
	if len(search) >= 3:
		items = Item.query.whooshee_search(search, order_by_relevance=25).all()
		if search is not None:
			return render_template('search.html',title='Home',items=items,search=search)
		else:
			flash('No items found!','danger')
			return redirect(url_for('main.index'))
	else:
		flash('Please enter longer word!','danger')
		return redirect(url_for('main.index'))

@main.route('/item/<int:item_id>',methods=['POST','GET'])
def item(item_id):
	item = Item.query.filter_by(id=item_id).first_or_404()
	reviews = Reviews.query.filter_by(item_id=item_id).all()
	form = AddToCart()
	form1 = WriteReview()
	if request.method == 'POST':
		if form.validate_on_submit():
			if current_user.is_authenticated:
				defined_item = Defined_Items(item_id=item.id,size=form.size.data,amount=form.amount.data)
				db.session.add(defined_item)
				db.session.commit() 
				new_cart_item = Cart_Items(cart_id=current_user.cart.id,defined_item_id=defined_item.id)
				db.session.add(new_cart_item)
				db.session.commit() 
				flash('Item has been added to your cart!','success')
				return redirect(url_for('main.item',item_id=item_id))
			else:
				flash('Please log in!','danger')
				return redirect(url_for('auth.login'))

		if form1.validate_on_submit():
			if current_user.is_authenticated:
				rating = form1.rating.data
				content = form1.content.data
				if len(content) > 500:
					flash('Text too long','danger')
					return redirect(url_for('main.item',item_id=item_id))
				else:
					Review = Reviews(user_id=current_user.id,item_id=item_id,rating=rating,comment=content)
					db.session.add(Review)
					db.session.commit() 
					flash('Review has been written!','danger')
					return redirect(url_for('main.item',item_id=item_id))
			else:
				flash('Please log in!','danger')
				return redirect(url_for('auth.login'))
	return render_template('item.html',title='Item',item=item,form=form,form1=form1,reviews=reviews)

@main.route('/item_by_type/<int:type_id>')
def item_type(type_id):

	items = Item.query.filter_by(item_type_id=type_id).all()
	search = Item_Type.query.filter_by(id=type_id).first().name;
	return render_template('types.html',title='Item',items=items,search=search)

@main.route('/cart',methods=['POST','GET'])
@login_required
def cart():

	Cart_Items.query.order_by(Cart_Items.date_added.desc())
	citems = Cart_Items.query.filter_by(cart_id=current_user.cart.id).all()

	amount = 0
	for citem in citems:
		amount += citem.defined_item.item.price * citem.defined_item.amount

	return render_template('cart.html',title='Cart',citems=citems,amount=amount)

@main.route('/remove_frm_cart/<int:item_id>',methods=['POST','GET'])
@login_required
def remove_item(item_id):

	item = Cart_Items.query.filter_by(id=item_id).first_or_404()
	db.session.delete(item)
	db.session.commit()

	flash('Item has been removed from your cart!','danger')

	return redirect(url_for('main.cart'))

@main.route('/clear_cart')
@login_required
def clear_cart():

	items= Cart_Items.query.all()
	if len(items):
		Cart_Items.query.delete()

		db.session.commit()

		flash(' All items has been removed from your cart!','danger')


		return redirect(url_for('main.cart'))
	else:
		flash('Cart is empty!','danger')
		return redirect(url_for('main.cart'))


@main.route('/order/payment',methods=['POST'])
@login_required
def payment():

    payment = paypalrestsdk.Payment({
    "intent": "sale",
    "payer": {
        "payment_method": "paypal"},
    "redirect_urls": {
        "return_url": "http://localhost:3000/payment/execute",
        "cancel_url": "http://localhost:3000/"},
    "transactions": [{
        "item_list": {
            "items": [{
                "name": "Order #",
                "sku": "12345",
                "price": "500.00",
                "currency": "USD",
                "quantity": 1}]},
        "amount": {
            "total": "500.00",
            "currency": "USD"},
        "description": "This is the payment transaction description."}]})

    if payment.create():
        print('Payment success!')
    else:
        print(payment.error)

    return jsonify({'paymentID' : payment.id})

@main.route('/order/execute',methods=['POST'])
@login_required
def execute():
	success = False
	payment = paypalrestsdk.Payment.find(request.form['paymentID'])
	
	if payment.execute({'payer_id' : request.form['payerID']}):
		print('Execute success!')
		success = True
	else:
		print(payment.error)

	return jsonify({'success' : success})

@main.route('/pay/<int:order_id>',methods=['POST','GET'])
@login_required
def pay(order_id):

	order = Orders.query.filter_by(id=order_id).first_or_404()
	customer = stripe.Customer.create(email=request.form['stripeEmail'], source=request.form['stripeToken'])
		
	charge = stripe.Charge.create(
		customer=customer.id,
		amount=int(order.price*100),
		currency='usd',
		description=f'Order#{order.id}'
		)


	order.paid = True;

	db.session.commit()

	flash('Order has been completed!','success')
	return redirect(url_for('main.orders'))

@main.route('/payment/<int:order_id>',methods=['POST','GET'])
@login_required
def order_payment(order_id):

	order = Orders.query.filter_by(id=order_id).first_or_404()

	if current_user.info.address is None:
		flash('Please add address to your profile info!','danger')
		return redirect(url_for('profile.profile_page'))

	else:

		return render_template('payment.html',order=order,pub_key=pub_key)

@main.route('/orders')
@login_required
def orders():
	
	orders = Orders.query.filter_by(user_id=current_user.id).all()
	Orders.query.order_by(Order_Items.date_added.desc())

	return render_template('orders.html',orders=orders)

@main.route('/checkout/<int:order_id>')
@login_required
def checkout(order_id):
	order = Orders.query.filter_by(id=order_id).first_or_404()

	return render_template('checkout.html',order=order)

@main.route('/make_order/<int:item_id>',methods=['POST','GET'])
@login_required
def make_order(item_id):

	items= Cart_Items.query.all()
	if len(items):
		order = Orders(user_id=current_user.id,paid=False)

		db.session.add(order)
		db.session.commit()

		order_items = Order_Items(defined_item_id=item_id,order_id=order.id)

		db.session.add(order_items)
		db.session.commit()

		amount = 0
		for item in order.order_items:
			amount += item.defined_item.item.price * item.defined_item.amount

		order.price = amount

		db.session.commit()

		return redirect(url_for('main.checkout',order_id=order.id))
	else:
		flash('Cart is empty!','danger')
		return redirect(url_for('main.cart'))

@main.route('/order_all')
@login_required
def order_all():

	items= Cart_Items.query.all()
	if len(items):
		order = Orders(user_id=current_user.id,paid=False)

		db.session.add(order)
		db.session.commit()

		amount = 0
		for item in current_user.cart.cart_items:

			amount += item.defined_item.item.price * item.defined_item.amount
			order_item = Order_Items(defined_item_id=item.defined_item.id,order_id=order.id)
			db.session.add(order_item)

		order.price = amount
		db.session.commit()
		return redirect(url_for('main.checkout',order_id=order.id))
	else:
		flash('Cart is empty!','danger')
		return redirect(url_for('main.cart'))

@main.route('/order_selected',methods=['POST','GET'])
@login_required
def order_selected():


	if request.method == 'POST':
		id_list = request.form.getlist('id')
		items= Cart_Items.query.all()
		if len(id_list):
				order = Orders(user_id=current_user.id,paid=False)

				db.session.add(order)
				db.session.commit()

				amount = 0


				for i in id_list:

					citem = Cart_Items.query.filter_by(id=i).first()
					amount += citem.defined_item.item.price * citem.defined_item.amount

					order_item = Order_Items(defined_item_id=citem.defined_item.id,order_id=order.id)

					db.session.add(order_item)
					db.session.commit()

				order.price = amount
				db.session.commit()

				return redirect(url_for('main.checkout',order_id=order.id))
		else:
			flash('You havent selected anything!','danger')
			return redirect(url_for('main.cart'))

@main.route('/cancel_order/<int:order_id>',methods=['POST','GET'])
@login_required
def cancel_order(order_id):

	order = Orders.query.filter_by(user_id=current_user.id,id=order_id).first()
	db.session.delete(order)
	db.session.commit()

	flash('Order has been removed!','danger')

	return redirect(url_for('main.orders'))

project/main/templates/cart.html
{% extends "index.html" %}
{% block content %}
<main>
	<div style="width: 100%">
	{% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="text-center alert alert-{{ category }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    <div class="cart_page" style="width: 100%">
	    <div class="sidebar row">
	    	<div class="sidebar-content">
	    		<div class="top-total">
	    			<div style="width: 100%;">
				    	<div><h7> Items In Cart: {{ citems|length }}</h7></div>
				    	<div><h7> Total price: {{ amount }}</h7></div>
			    	</div>
			    	<div style="margin-left: 20px; ">
						<a href="{{ url_for('main.clear_cart') }}">
	            			<button type="button" style="background-color: red !important;" class="clear-cart-btn btn btn-lg btn-primary btn-block text-uppercase">
	            				Clear Cart
	            			</button>
            			</a>
        			 </div>
        			 <div style="margin-left: 20px;">
						<a href="{{ url_for('main.order_all') }}">
	            			<button type="button" class="clear-cart-btn btn btn-lg btn-primary btn-block text-uppercase">
	            				Order All
	            			</button>
            			</a>
        			 </div>
        			 <form method="POST" action="/order_selected">
        			 <div style="margin-left: 20px;">
	            			<button type="submit" class="clear-cart-btn btn btn-lg btn-primary btn-block text-uppercase">
	            				Order Selected
	            			</button>
        			 </div>
		    	</div>
		    	<div style="margin-top: 25px;">
		    		<input type="checkbox" onClick="toggle(this)" /> Toggle All<br/>
		    	</div>
		    	<div class="end">
		    	</div>
	    	</div>
	    </div>
		<div class="item_frame_wrapper cw">
				{% for citem in citems %}
		        <div class="row" id="ifwc" >
		            <div class="item_frame" style="width: 100%">
						<div class="cart_content">
		            		<div class="cart_item">
			            		<div class="row text-center">
		            				<div class="top">		            					
		            						<input type="checkbox" value="{{ citem.id }}" name="id">
			            					<div class="x-div">
			            						<a href="{{ url_for('main.remove_item',item_id=citem.id) }}">
			            							<span class="close">
			            								x
			            							</span>
			            						</a>
			            					</div>	            						
		            				</div>
		            			</div>
		            		
		            		<div class="row text-center cart-btns">
		            			<div class=" col-md cart_image_div">
		            				<div class="" style="height: 100%; margin-top: 10px">
		            					<div class="cart-name">
			            					<div><h5>{{ citem.defined_item.item.name }}</h5></div>
			            					<div style="margin-bottom: 10px"><h7> Added: {{ citem.date_added.strftime('%Y-%m-%d') }}</h7></div>
		            					</div>
		            				<img src="{{ url_for('main.static', filename='img/'+ citem.defined_item.item.name + '/' + citem.defined_item.item.image_file) }}">
		            				</div>
		            			</div>
		            			<div class="col-md" style="padding-top: 10px;">
		            				<div><p>{{ citem.defined_item.item.description }}</p></div>
		            				<div><h7> Size: {{ citem.size }}</h7></div>
		            				<div style="padding-top: 15px;"><h5> Price: {{ citem.defined_item.item.price }}</h5></div>
		            				<div><h7> Amount: {{ citem.defined_item.amount }}</h7></div>	    				
		            			</div>
								<div class="col-md" style="width: 100%;">
									<div class="remove_frm_cart text-center">
										<a href="{{ url_for('main.make_order',item_id=citem.defined_item.id) }}">
											<button type="button" class="btn btn-lg btn-primary btn-block text-uppercase">Order Item</button>
										</a>
									</div>
									<div class="remove_frm_cart text-center">
										<a href="{{ url_for('main.item',item_id=citem.defined_item.item.id) }}">
											<button type="button" class="btn btn-lg btn-primary btn-block text-uppercase">View Item</button>
										</a>
									</div>
								</div>
								</div>  
		            		</div>
		            	</div>
		            </div>
				</div>
	          	{% endfor %}
	          	</form>
		</div>
		</div>
	</div>
</main>
	<script language="JavaScript">
	function toggle(source) {
  checkboxes = document.getElementsByName('id');
  for(var i=0, n=checkboxes.length;i<n;i++) {
    checkboxes[i].checked = source.checked;
  }
}
	</script> 
{% endblock content %}

project/main/templates/checkout.html
{% extends "index.html" %}
{% block content %}
<main>
	<div class="checkout-content">
		<div class="" style="width: 100%">
		{% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="text-center alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        </div>
		<div class="checkout-panel">
			<div class="checkout-panel-content">
				<h5>Order Items</h5>
				<div class="checout-order-items">
					<ul>
						{% for item in order.order_items %}
					  		<li>
					  			<div class="checkout-list-items">
					  				<h5> {{ item.defined_item.amount }} X {{ item.defined_item.item.name }}</h5>
					  				<img src="{{ url_for('main.static', filename='img/'+ item.defined_item.item.name + '/' + item.defined_item.item.image_file) }}" class="checkout-item-img">
					  				<h7> Size: {{ item.defined_item.size }}</h7>
					  				<h7> Price: {{ item.defined_item.item.price }}</h7>
					  				<h7>{{ item.defined_item.item.description }}</h7>
					  			</div>
					  		</li>
					  		<hr>
					  	{% endfor %}
					</ul>
					<div class="checkout-total">
						<h6> Amount of items: {{ order.order_items |length }}</h6>
						<h6> Total price: {{ order.price }}</h6>
					</div>
					<div class="form-group obt">
						<a href="{{ url_for('main.order_payment',order_id=order.id) }}">
	            			<button type="button" class="payment-btn btn btn-lg btn-primary btn-block text-uppercase">
	            				Proceed To Payment
	            			</button>
            			</a>
        			 </div>
				</div>
			</div>	
		</div>
	</div>
</main>
{% endblock content %}

project/main/templates/index.html
<!DOCTYPE html>
<html lang="en" class="full-height">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
	  <link rel="stylesheet" type="text/css" href="{{ url_for('main.static', filename='css/main.css') }}">

    <title>{{ title }}</title>
  </head>
    <body class="hm-gradient">
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark mb-4">
             <!-- <a class="navbar-brand" href="#">Navbar</a>-->
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                      <li class="nav-item active">
                          <a class="nav-link" href="{{ url_for('main.index') }}">Home <span class="sr-only">(current)</span></a>
                      </li>
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search 
                              </a>
                          <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                            {% for type in types %}
                              <a class="dropdown-item" href="{{ url_for('main.item_type',type_id=type.id) }}">{{type.name}}</a>
                            {% endfor %}
                          </div>
                      </li>
                  </ul>
              </div>
                  <div class="cart">    
                    <a href="{{ url_for('main.cart') }}" class="nav-link mr-auto"><i class="fa fa-shopping-cart fa-lg" style="color: white"></i>
                      {% if current_user.is_authenticated %}
                        {% if current_user.cart.cart_items|length > 0 %}
                        <span class="cart-span dot text-center"><h7 class="item-number">{{ current_user.cart.cart_items|length }}</h7></span>
                        {% endif %}
                      {% endif %}
                    </a>
                  </div>
                    <!-- Searchbar  -->
                    <div>
                    <a class="nav-link dropdown-toggle" style="color: white;" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="icon-search fa fa-search fa-lg" aria-hidden="true" style="color:white"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-unique" aria-labelledby="navbarDropdownMenuLink">
                      <form class="form-inline" method="GET" action="/search">
                        <input style="color: black;" class="searchbar" name="search" type="text" placeholder="Search" aria-label="Search">
                      </form>
                    </div>
                    </div>
                  <ul class="navbar-nav mr-auto">
                    <!-- Profile dropdown -->
                    <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user fa-lg"></i> 
                              </a>
                          <div class="dropdown-menu dropdown-menu-right dropdown-unique" aria-labelledby="navbarDropdownMenuLink">
                              {% if not current_user.is_authenticated %}
                              <a class="dropdown-item" href="{{ url_for('auth.register') }}">Register</a>
                              <a class="dropdown-item" href="{{ url_for('auth.login') }}">Log In</a>
                              {% endif %}
                              {% if current_user.is_authenticated %}
                              <a class="dropdown-item" href="{{ url_for('profile.profile_page') }}">Profile</a>
                              <a class="dropdown-item" href="{{ url_for('main.orders') }}">Orders</a>
                              <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Log Out</a>
                              {% endif %}
                          </div>
                      </li>
                  </ul>
        </nav>
    {% block content %}{% endblock %}
    <!-- Optional JavaScript -->
    <script src="{{ url_for('static', filename='js/main.js') }}" type="text/javascript"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

project/main/templates/main.html
{% extends "index.html" %}
{% block content %} 
<main>
      <div class="" style="width: 100%">
    {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="text-center alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        </div>
      <div class="item_wrapper">
        <div class="row row_wrapper">
          {% for item in items %}
            <div class="col-sm-3 text-center board" id="column">
              <a href="{{ url_for('main.item',item_id=item.id) }}" class="panel_button">
                <div class="panel">
                  <div class="item_name"><h3 >{{ item.name }}</h3></div>
                  <div class="photo_wrapper">
                    <img src="{{ url_for('main.static', filename='img/'+ item.name + '/' + item.image_file)  }}">
                  </div>
                  <div>
                    <h5>Price: {{ item.price }}</h5>
                  </div>
                  <div class="buy_button">
                    <button class="btn btn-lg btn-primary btn-block text-uppercase">Buy</button>
                  </div>
                </div>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
    </main>
{% endblock content %}

project/main/templates/orders.html
{% extends "index.html" %}
{% block content %}
<main>
		<div class="" style="width: 100%">
		{% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="text-center alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        </div>
        <div class="orders-content">
          <div class="order-panel" style="padding:10px;"><h7> Orders: {{ orders|length }}</h7></div>
          {% for order in orders %}
              <div class="order-panel">
                  <div class="order-panel-content">
                    <h7> Order: #{{ order.id }}</h7><h7 style="margin-left: 2px;"> | {{ order.date.strftime('%Y-%m-%d') }}</h7>
                    <br>
                    {% if order.paid %}
                    <h7>Paid: Yes</h7>
                    {% else %}
                    <h7>Paid: No</h7>
                    {% endif %}
                    <ul>
                    {% for item in order.order_items %}
                        <li>
                          <div class="checkout-list-items">
                            <h5> {{ item.defined_item.amount }} X {{ item.defined_item.item.name }}</h5>
                            <img src="{{ url_for('main.static', filename='img/'+ item.defined_item.item.name + '/' + item.defined_item.item.image_file) }}" class="checkout-item-img">
                            <h7> Size: {{ item.defined_item.size }}</h7>
                            <h7> Price: {{ item.defined_item.item.price }}</h7>
                            <h7>{{ item.defined_item.item.description }}</h7>
                          </div>
                        </li>
                        <hr>
                    {% endfor %}
                    </ul>
                    <div class="checkout-total">
                      <h6> Amount of items: {{ order.order_items |length }}</h6>
                      <h6> Total price: {{ order.price }}</h6>
                    </div>
                    <div class="orders-btns">
                    {% if order.paid %}
                    <div class="form-group obt">
                        <button disabled type="button" class="orders-payment-btn btn btn-lg btn-primary btn-block text-uppercase">
                          Proceed To Payment
                        </button>
                   </div>
                    {% else %}
                <div class="form-group obt">
                  <a href="{{ url_for('main.order_payment',order_id=order.id) }}">
                    <button type="button" class="orders-payment-btn btn btn-lg btn-primary btn-block text-uppercase">
                      Proceed To Payment
                    </button>
                  </a>
               </div>
                <div class="form-group obt">
                  <a href="{{ url_for('main.cancel_order',order_id=order.id) }}">
                    <button type="button"  style="background-color: red !important;" class="orders-payment-btn btn btn-lg btn-primary btn-block text-uppercase">
                      Cancel Order
                    </button>
                  </a>
               </div>
                  {% endif %}
                  </div>
                  </div>
              </div>
          {% endfor %}
        </div>
</main>
{% endblock content %}

project/main/templates/payment.html
{% extends "index.html" %}
{% block content %}
<main>
	<div class="checkout-content">
		<div class="" style="width: 100%">
		{% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="text-center alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        </div>
		<div class="checkout-panel">
			<div class="payment-panel-content">
				<h5 style="padding-top: 15px;">Payment</h5>
				<h7 style="padding-bottom: 15px;">Total Price: {{ order.price }}</h7>

						<script src="https://www.paypalobjects.com/api/checkout.js"></script>

						<script>
						    var CREATE_PAYMENT_URL  = 'http://127.0.0.1:5000/order/payment';
						    var EXECUTE_PAYMENT_URL = 'http://127.0.0.1:5000/order/execute';

						    paypal.Button.render({

						        env: 'sandbox', // Or 'sandbox'

						        commit: true, // Show a 'Pay Now' button

						        payment: function() {
						            return paypal.request.post(CREATE_PAYMENT_URL).then(function(data) {
						                return data.paymentID;
						            });
						        },

						        onAuthorize: function(data) {
						            return paypal.request.post(EXECUTE_PAYMENT_URL, {
						                paymentID: data.paymentID,
						                payerID:   data.payerID
						            }).then(function(res) {

						                console.log(res.success)
						                // The payment is complete!
						                // You can now show a confirmation message to the customer
						            });
						        }

						    }, '#paypal-button');
						</script>
						<div style="padding-bottom: 20px; padding-top: 10px;">
							<form action="{{ url_for('main.pay',order_id=order.id) }}" method="POST">
					          <script
					            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
					            data-key="{{ pub_key }}"
					            data-amount="{{ order.price * 100}}"
					            data-name="Demo Site"
					            data-description="Widget"
					            data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
					            data-locale="auto">
					          </script>
					        </form>
				        </div>
        			  <div class="form-group obt">
	                  <a href="{{ url_for('main.cart') }}">
	                    <button type="button" style="background-color: red !important;" class="payment-btn btn btn-lg btn-primary btn-block text-uppercase">
	                      Cancel
                    	</button>
                  	</a>
               </div>
			</div>	
		</div>
	</div>
</main>
{% endblock content %}